const scenes=[
{label:'OPENING · THE IMPOSSIBLE WALL',steps:0,html:`<span class="kicker">A five-minute quantum story</span><h1 class="hero">Can something pass through a wall?</h1><p class="sub">In everyday life, never. In the quantum world, <span class="accent">sometimes.</span></p><div class="wall-demo"><div class="wall-label">ENERGY BARRIER</div><div class="ball"></div><div class="wall"></div></div>`},
{label:'01 · CLASSICAL INTUITION',steps:5,html:`<span class="kicker">First: the familiar world</span><h2 class="head">A ball needs enough energy<br>to cross a hill.</h2><div class="hill-diagram"><svg viewBox="0 0 1000 350" role="img" aria-label="Ball approaching an energy hill"><path class="hill-path" d="M35 285 C210 285 240 275 330 275 C430 275 445 70 555 70 C665 70 680 275 775 275 C860 275 900 285 965 285"/><line class="energy-line reveal" x1="55" y1="155" x2="945" y2="155"/><text class="arrow-energy reveal" x="65" y="140">BALL'S ENERGY: BELOW THE PEAK</text><circle class="diagram-ball reveal" cx="250" cy="254" r="22"/><path class="energy-line reveal" d="M270 232 Q350 165 415 185"/><text class="arrow-energy reveal" x="455" y="48">ENERGY BARRIER</text></svg></div>`},
{label:'02 · THE QUANTUM SHIFT',steps:2,html:`<div class="split"><div><span class="kicker">Now shrink everything</span><h2 class="head">A particle is not just a tiny ball.</h2><p class="sub reveal">An electron is described by a <span class="cyan">wave of possibilities</span>, showing where it might be found.</p></div><div class="wavebox"><canvas data-wave="free"></canvas><div class="diagram-label left">PROBABILITY WAVE</div></div></div>`},
{label:'03 · TUNNELING',steps:3,html:`<span class="kicker">The key idea</span><h2 class="head">The wave does not stop instantly.</h2><p class="sub reveal">Inside the barrier it fades, but may not reach zero.</p><div class="wavebox"><canvas data-wave="tunnel"></canvas><div class="barrier"><span>BARRIER</span></div><div class="diagram-label left">INCOMING</div><div class="diagram-label right">SMALL CHANCE BEYOND</div></div>`},
{label:'03B · MANIM VISUAL',steps:0,html:`<span class="kicker">Watch the idea happen</span><h2 class="head">Wave → barrier → smaller wave.</h2><div class="video-frame"><video src="media/quantum_tunneling.mp4" autoplay muted loop playsinline></video><div class="video-badge">7 SEC · MADE WITH MANIM</div></div>`},
{label:'04 · WHAT ACTUALLY HAPPENS',steps:3,html:`<span class="kicker">No secret tunnel</span><h2 class="head">Measure many identical particles…</h2><div class="cards"><div class="card reveal"><span class="num">MOST</span><b>bounce back</b><p>The particle is detected before the barrier.</p></div><div class="card reveal"><span class="num">A FEW</span><b>appear beyond</b><p>They are detected on the other side.</p></div><div class="card reveal"><span class="num">NEVER</span><b>half a particle</b><p>Each measurement finds one whole particle.</p></div></div>`},
{label:'05 · THE ODDS',steps:2,html:`<span class="kicker">What changes the chance?</span><h2 class="head">Thinner and lower barriers<br>are easier to tunnel through.</h2><div class="prob"><div class="probbar reveal" style="height:92%"><strong>more likely</strong><label>thin barrier</label></div><div class="probbar reveal"><strong>less</strong><label>medium</label></div><div class="probbar reveal"><strong>rare</strong><label>thick</label></div><div class="probbar reveal"><strong>very rare</strong><label>very thick</label></div></div>`},
{label:'06 · WE CAN SEE ITS EFFECTS',steps:2,html:`<span class="kicker">A microscope built on tunneling</span><h2 class="head">A tiny current maps individual atoms.</h2><p class="sub reveal">In a scanning tunneling microscope, electrons cross a microscopic gap. The current changes dramatically with distance, turning the surface into an image.</p><div class="stm"><div class="stm-meter"><span>tunneling current</span><b>0.82 nA</b><i></i></div><div class="stm-tip"><span>conductive tip</span></div><div class="stm-gap"><span>tiny vacuum gap</span><i></i><i></i><i></i></div><div class="stm-surface"><span>sample surface</span><div class="atom-row"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="atom-row lower"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="stm-caption"><b>Closer tip</b><span>stronger current</span><em>→</em><b>Farther tip</b><span>weaker current</span></div></div>`},
{label:'07 · WHY IT MATTERS',steps:3,html:`<span class="kicker">Not just a thought experiment</span><h2 class="head">Tunneling quietly shapes our world.</h2><div class="apps"><div class="app reveal"><div class="icon">☀</div><h3>Stars</h3><p>Helps nuclei get close enough for fusion.</p></div><div class="app reveal"><div class="icon">⌁</div><h3>Electronics</h3><p>Enables devices and creates leakage in tiny chips.</p></div><div class="app reveal"><div class="icon">⌕</div><h3>Microscopy</h3><p>Lets us image surfaces atom by atom.</p></div></div>`},
{label:'CLOSE · ONE IDEA TO KEEP',steps:3,html:`<div class="final"><div><span class="kicker">Quantum tunneling</span><h1 class="hero"><span class="pulse-dot"></span> A particle can cross a barrier it cannot classically cross.</h1><p class="sub reveal">Because quantum objects behave like <span class="cyan">waves of probability.</span></p><p class="sub reveal" style="margin-top:1rem">Impossible classically. <span class="accent">Possible quantum mechanically.</span></p></div></div>`}
];
let index=0,raf=[];const stage=document.querySelector('#stage'),counter=document.querySelector('#counter'),progress=document.querySelector('#progress'),indexButton=document.querySelector('#index-button'),indexOverlay=document.querySelector('#index-overlay'),indexList=document.querySelector('#index-list'),indexClose=document.querySelector('#index-close');
scenes.forEach((s,i)=>{const el=document.createElement('section');el.className='scene';el.innerHTML=s.html;stage.appendChild(el);s.el=el;const d=document.createElement('i');progress.appendChild(d)});
scenes.forEach((s,i)=>{const b=document.createElement('button');b.className='index-item';b.type='button';b.innerHTML=`<span class="index-num">${String(i+1).padStart(2,'0')}</span><span class="index-name">${s.label.replace(/^[^·]+·\s*/,'')}</span>`;b.addEventListener('click',()=>{show(i);toggleIndex(false)});indexList.appendChild(b)});
function show(i){if(i<0||i>=scenes.length)return;raf.forEach(cancelAnimationFrame);raf=[];scenes[index].el.classList.remove('active');index=i;scenes[i].el.classList.add('active');update();const v=scenes[i].el.querySelector('video');if(v){v.currentTime=0;v.play().catch(()=>{})}startCanvases(scenes[i].el)}
function update(){counter.textContent=`${String(index+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;[...progress.children].forEach((d,i)=>d.classList.toggle('on',i===index));[...indexList.children].forEach((b,i)=>b.classList.toggle('current',i===index));}
function next(){show(index+1)}function prev(){show(index-1)}
function toggleIndex(force){const open=typeof force==='boolean'?force:!indexOverlay.classList.contains('open');indexOverlay.classList.toggle('open',open);indexOverlay.setAttribute('aria-hidden',String(!open));indexButton.setAttribute('aria-expanded',String(open))}
indexButton.addEventListener('click',e=>{e.stopPropagation();toggleIndex()});indexClose.addEventListener('click',()=>toggleIndex(false));indexOverlay.addEventListener('click',e=>{if(e.target===indexOverlay)toggleIndex(false)});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='i'){e.preventDefault();toggleIndex();return}if(e.key==='Escape'){toggleIndex(false);return}if(indexOverlay.classList.contains('open'))return;if(['ArrowRight',' ','PageDown'].includes(e.key)){e.preventDefault();next()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev()}if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.()});stage.addEventListener('click',e=>e.clientX>innerWidth*.3?next():prev());
function startCanvases(root){root.querySelectorAll('canvas').forEach(canvas=>{const ctx=canvas.getContext('2d'),mode=canvas.dataset.wave;function draw(t){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr)}ctx.clearRect(0,0,w,h);ctx.lineWidth=3;ctx.shadowBlur=14;ctx.shadowColor='#5fb6c4';ctx.strokeStyle='#5fb6c4';ctx.beginPath();for(let x=0;x<w;x++){let amp=52*Math.exp(-Math.pow((x-(w*.28+(t*.075)%(w*.78)))/(w*.13),2));if(mode==='tunnel'){if(x>w*.49&&x<w*.62)amp*=Math.exp(-(x-w*.49)/(w*.045));if(x>=w*.62)amp*=.26}let y=h*.55+Math.sin(x*.095-t*.009)*amp;ctx.lineTo(x,y)}ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#a89a8844';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h*.55);ctx.lineTo(w,h*.55);ctx.stroke();raf.push(requestAnimationFrame(draw))}draw(0)})}
show(0);
